name: Build

on: [push, pull_request]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up JDK
              uses: actions/setup-java@v1
              with:
                java-version: '11'
            
            - name: Build with Maven
              run: mvn test

            - name: Deploy
              env:
                TOKEN: ${{ secrets.GITHUBTOKEN }}
              run: |
                echo "<settings><servers><server><id>github</id><username>JeffreyRiggle</username><password>\${env.TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
                REPO="gh::default::https://maven.pkg.github.com/${GITHUB_REPOSITORY}"
                mvn deploy -Drevision="${GITHUB_RUN_NUMBER}"